[build]
target = "x86_64-unknown-linux-musl"
rustflags = ["-Clinker=rust-lld"]

[target.x86_64-unknown-linux-gnu]
#linker = "/usr/local/opt/x86_64-unknown-linux-gnu-gcc"

[target.x86_64-unknown-linux-musl]
linker = "rust-lld"
rustflags = ["-C", "target-feature=-crt-static"]